# Generated by Django 3.2.4 on 2021-06-21 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
