# Generated by Django 3.2.4 on 2021-06-23 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='decomplete',
            field=models.BooleanField(default=True),
        ),
    ]
