# Generated by Django 3.2.4 on 2021-06-23 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_task_decomplete'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='decomplete',
        ),
    ]
